#!/bin/bash
# by Stefan Ruedisuehli, 2015-08-25

DIRECTORY_CHECK=true

USAGE="Usage: $(basename ${0}) <FILE(S)>

Assert the existance of one or more files."

main()
{
    # Eval inargs
    local narg_min=1
    [ ${#} -lt ${narg_min} ] && { echo "${USAGE}" >&2; return 1; }

    # Check files
    local stat=0
    for file in "${@}"
    do
        if [ ! -f "${file}" ]
        then
            echo -n "error: file not found: '${file}'" >&2
            if ${DIRECTORY_CHECK}
            then
                if [[ -d "${file}" ]]
                then
                    echo -n " (is a directory)" >&2
                else
                    echo -n " (is not a directory, either)" >&2
                fi
            fi
            echo
            stat=1
        fi
    done
    return ${stat}
}

main "${@}"
