#!/bin/bash
# by Stefan Ruedisuehli, 2015-08-21

DBG=false

USAGE="usage: $(basename ${0}) <WIDTH> <ANGLE> <DY> <OUTFILE> <LABEL>"

main()
{
    # Eval inargs
    local narg_exp=5
    if [ ${#} -ne ${narg_exp} ]
    then
        [[ $# -gt 0 ]] && echo "error: wrong arguments (${#}/${narg_exp}): $@" >&2
        echo "${USAGE}"
        return  1
    fi
    local width="${1}"
    local angle="${2}"
    local dy="${3}"
    local outfile="${4}"
    local label="${5}"

    local labelfile="_label.${group}.png"
    local size="${width}x$((width/10))"
    local pts="$((width*7/100))"

    ${DBG} && echo "------------------------------"
    ${DBG} && echo "${0} ${@}"
    ${DBG} && echo "------------------------------"
    ${DBG} && echo "label     : ${label}"
    ${DBG} && echo "width     : ${width}"
    ${DBG} && echo "angle     : ${angle}"
    ${DBG} && echo "dy        : ${dy}"
    ${DBG} && echo "outfile   : ${outfile}"
    ${DBG} && echo "------------------------------"
    ${DBG} && echo "labelfile : ${labelfile}"
    ${DBG} && echo "size      : ${size}"
    ${DBG} && echo "pts       : ${pts}"
    ${DBG} && echo "------------------------------"

    convert -verbose                    \
        -size ${size}                   \
        xc:white                        \
        -fill black                     \
        -font Palatino-Bold             \
        -pointsize ${pts}               \
        -gravity center                 \
        -draw "text 0,${dy} '${label}'" \
        -rotate ${angle}                \
        PNG32:"${outfile}"
}

main "${@}"
