#!/bin/bash

usage="usage: $0 START END INCREMENT COMMAND

Loop over a range of dates (UTC) in steps increments of multiples of hours
The expected date format is YYYYMMDDHH, i.e. %Y%m%d%H.
To use the date components in the command, use \$DATE, \$YYYY, \$MM, \$DD, and/or \$HH."

[ $# -lt 3 ] && { echo -e "${usage}" >&2; exit 1; }

date_start=$1
date_end=$2
increment=$3
shift 3
cmd="$@"

export TZ=UTC

# Check dates and increment
echo "${date_start}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9]'
err="invalid start date ${date_start}, expect format YYYYMMDDHH i.e. %Y%m%d%H"
[ $? -ne 0 ] && { echo "${err}" >&2; exit 2; }
echo "${date_end}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9]'
err="invalid end date ${date_end}, expect format YYYYMMDDHH i.e. %Y%m%d%H"
[ $? -ne 0 ] && { echo "${err}" >&2; exit 2; }
err="invalid non-zero increment ${increment}"
[ ${increment} -eq 0 ] && { echo "${err}" >&2; exit 2; }

# Loop over dates (dont use while loop to avoid infinite loop)
date_curr="$(TZ=UTC date +%Y%m%d%H -d "${date_start:0:8} ${date_start:8:2} - ${increment} hours")"
iter_max=$((date_end - date_start))
for iter_i in $(seq 0 $iter_max)
do
    # Increment date
    date_curr="$(TZ=UTC date +%Y%m%d%H -d "${date_curr:0:8} ${date_curr:8:2} + ${increment} hours")"
    yyyy=${date_curr:0:4}
    mm=${date_curr:4:2}
    dd=${date_curr:6:2}
    hh=${date_curr:8:2}

    # Insert date components in comment
    cmd_i="$(echo $cmd | sed \
            -e "s/\${\?DATE}\?/${date_curr}/g" \
            -e "s/\${\?YYYY}\?/${yyyy}/g" \
            -e "s/\${\?MM}\?/${mm}/g" \
            -e "s/\${\?DD}\?/${dd}/g" \
            -e "s/\${\?HH}\?/${hh}/g")"

    # Execute command
    eval $cmd_i || exit $?

    # Are we done yet?
    [ "${date_curr}" == "${date_end}" ] && break
done


