#!/bin/bash

OPEN=display

main()
{
    local dir="$1"
    local suffix=""
    [[ $# -gt 1 ]] && suffix="$2"
    local file="$(\ls -dtr "${dir}"/*"${suffix}" | tail -1)"
    [[ "${file}" != "" ]] && ${OPEN} "${file}"
}

main "$@"
