#!/bin/bash
# by Stefan Ruedisuehli, 2015-08-24

USAGE="Usage: $(basename ${0}) <STRING(S)>

Convert one or more strings to lowercase."

main()
{
    local nargs_min=1
    [ ${#} -lt ${nargs_min} ] && { echo "${USAGE}" >&2; return 1; }

    for str in ${@}
    do
        echo "${str}" | tr '[:upper:]' '[:lower:]'
    done
}

main "${@}"
