#!/bin/bash

OPEN=exo-open

main()
{
    local dir="$1"
    local suffix=""
    [[ $# -gt 1 ]] && suffix="$2"
    local file="$(\ls -dtr "${dir}"/*"${suffix}" | tail -1)"
    if [[ "${file}" != "" ]]
    then
        echo "${OPEN}" "${file}"
        ${OPEN} "${file}"
    fi
}

main "$@"
