#!/bin/bash
# src: http://stackoverflow.com/a/19358402/4419816

USAGE="Usage: $(basename "${0}") <INFILE(S)> <OUTFILE>"

main()
{
    if [[ ${#} -lt 2 ]]
    then
        echo "${USAGE}"
        return 1
    fi
    infiles=("${@}")
    n=$((${#infiles[@]}-1))
    outfile="${infiles[$n]}"
    unset infiles[${n}]

    assert_file "${infiles[@]}" || return ${?}

    if [ -f "${outfile}" ]
    then
        echo "error: '${outfile}' already exists!" >&2
        return 1
    fi

    echo "PDFMERGE: ${infiles[@]} -> ${outfile}"

    gs -q \
        -dBATCH \
        -dNOPAUSE \
        -sDEVICE=pdfwrite \
        -dPDFSETTINGS=/prepress \
        -sOutputFile="${outfile}" \
        "${infiles[@]}" >/dev/null 2>&1
    if [ ${?} -ne 0 ]
    then
        echo "Errors occurred during merging!" >&2
        return 1
    fi
}


command -v assert_file >/dev/null || {
    assert_file()
    {
        local path="${1}"
        [ -f "${path}" ] || return 1
        return 0
    }
}

main "${@}"
