#!/bin/bash
# Print command to show and run a command

main()
{
    echo 'DRY="${DRY:-false}"'
    echo ''
    echo 'run()'
    echo '{'
    echo '    local cmd=("${@}")'
    echo '    echo "RUN $(printf "%q " "${cmd[@]}")" >&2'
    echo '    ${DRY} && return 0'
    echo '    \eval $(printf "%q " "${cmd[@]}")'
    echo '}'
}

main "${@}"
