#!/bin/bash

USAGE="usage: $(basename ${0}) \$0"

main()
{
    [ ${#} -ne 1 ] && { echo "${USAGE}" >&2; return 1; }

    # Fetch calling script with relative path
    caller_rel="${1}"

    # Convert relative to absolute path
    caller_abs="$(readlink -f "${caller_rel}")"

    # Return the path to the directory
    dirname "${caller_abs}"

    return 0
}

main "${@}"
