#!/bin/bash
# by Stefan Ruedisuehli, 2015-08-21

USAGE="Usage: $(basename $0) (true|false)"

main()
{
    narg=1
    [ ${#} -ne $narg ] && { echo "${USAGE}" >&2; return 1; }

    case ${1} in
    true)
        echo false
    ;;
    false)
        echo true
    ;;
    *)
        echo "${USAGE}"
        return 2
    ;;
    esac
}

main "${@}"
