#!/bin/bash
# by Stefan Ruedisuehli, 2015-08-24

USAGE="Usage: $(basename ${0}) <STRING(S)>

Convert one or more strings to uppercase."

main()
{
    local nargs_min=1
    [ $# -lt ${nargs_min} ] && { echo "${USAGE}" >&2; exit 1; }

    for str in ${@}
    do
        echo "${str}" | tr '[:lower:]' '[:upper:]'
    done
}

main "${@}"
