#!/bin/bash

EXE="vim"
SESSION="./session"

main()
{
    files=($(eval echo $(\cat "${SESSION}" | grep '^[^#]' | sed "s/['\"]/\\\&/g"))) || return ${?}
    ${EXE} "${files[@]}" || return ${?}
}

main "$@"
