#!/bin/bash

SESSION="./session"

main()
{
    files=($(eval echo $(\cat "${SESSION}" | grep '^[^#]' | sed "s/['\"]/\\\&/g"))) || return ${?}
    TERM=screen-256color vim "${files[@]}" || return ${?}
}

main "$@"
