#!/bin/bash
# by Stefan Ruedisuehli, 2015-08-21

USAGE="$(basename ${0}) N NUMBER(S)
 - N: length of returned padded numbers
 - NUMBER(S): list of numbers to be zero-padded"

main()
{
    # Eval inargs
    nargs_min=2
    [ ${#} -lt ${nargs_min} ]] && { echo "${USAGE}"; return 1; }

    local n="${1}"
    shift
    local list=(${@})

    # Add leading zeros
    for num in ${list[@]}
    do
        printf "%0${n}i" $((num))
    done
}

main "${@}"
